apiVersion: batch/v1
kind: Job
metadata:
  name: traffic-generator-load-test
  labels:
    app: traffic-generator
    type: load-test
spec:
  template:
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["k6", "run"]
        args:
        - "--env"
        - "BASE_URL=http://demo-app-canary-metrics:80"
        - "/scripts/load-test.js"
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: scripts
        configMap:
          name: k6-scripts
      restartPolicy: Never
  backoffLimit: 1
